In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv(r"C:\Users\rupak\Downloads\Rsip2020-Chronic Kidney Disease(CKD)\dataset.csv")

In [3]:
dataset.isnull().any()

age                        True
Blood Pressure             True
Specific Gravity           True
Albumin                    True
Sugar                      True
Red Blood Cells            True
Pus Cell                   True
Pus Cell clumps            True
Bacteria                   True
Blood Glucose Random       True
Blood Urea                 True
Serum Creatinine           True
Sodium                     True
Potassium                  True
Hemoglobin                 True
Packed Cell Volume         True
White Blood Cell Count     True
Red Blood Cell Count       True
Hypertension               True
Appetite                   True
Pedal Edema                True
Anemia                     True
Class                     False
dtype: bool

In [4]:
dataset['age'].fillna(dataset['age'].median(),inplace=True)

In [5]:
dataset['Blood Pressure'].fillna(dataset['Blood Pressure'].mode()[0],inplace=True)

In [6]:
p=dataset['Specific Gravity'].median()
p

1.02

In [7]:
dataset['Albumin'].fillna(dataset['Albumin'].mode()[0],inplace=True)

In [8]:
dataset['Sugar'].fillna(dataset['Sugar'].median(),inplace=True)

In [9]:
dataset['Red Blood Cells'].fillna(dataset['Red Blood Cells'].mode()[0],inplace=True)

In [10]:
dataset['Pus Cell'].fillna(dataset['Pus Cell'].mode()[0],inplace=True)

In [11]:
dataset['Pus Cell clumps'].fillna(dataset['Pus Cell clumps'].mode()[0],inplace=True)

In [12]:
dataset['Bacteria'].fillna(dataset['Bacteria'].mode()[0],inplace=True)

In [13]:
dataset['Blood Glucose Random'].fillna(dataset['Blood Glucose Random'].median(),inplace=True)

In [14]:
dataset['Blood Urea'].fillna(dataset['Blood Urea'].mode()[0],inplace=True)

In [15]:
dataset['Serum Creatinine'].fillna(dataset['Serum Creatinine'].median(),inplace=True)

In [16]:
dataset['Sodium'].fillna(dataset['Sodium'].mode()[0],inplace=True)

In [17]:
dataset['Potassium'].fillna(dataset['Potassium'].median(),inplace=True)

In [18]:
dataset['Hemoglobin'].fillna(dataset['Hemoglobin'].mode()[0],inplace=True)

In [19]:
dataset['Packed Cell Volume'].unique()

array(['44', '38', '31', '32', '35', '39', '36', '33', '29', '28', nan,
       '16', '24', '37', '30', '34', '40', '45', '27', '48', '\t?', '52',
       '14', '22', '18', '42', '17', '46', '23', '19', '25', '41', '26',
       '15', '21', '43', '20', '\t43', '47', '9', '49', '50', '53', '51',
       '54'], dtype=object)

In [20]:
p=dataset['Packed Cell Volume'].mode()[0]
p

'41'

In [21]:
dataset['Packed Cell Volume'].replace(['\t?','\t43'],[41,41],inplace=True)

In [22]:
dataset['Packed Cell Volume'].fillna(dataset['Packed Cell Volume'].mode()[0],inplace=True)

In [23]:
dataset['White Blood Cell Count'].unique()

array(['7800', '6000', '7500', '6700', '7300', nan, '6900', '9600',
       '12100', '4500', '12200', '11000', '3800', '11400', '5300', '9200',
       '6200', '8300', '8400', '10300', '9800', '9100', '7900', '6400',
       '8600', '18900', '21600', '4300', '8500', '11300', '7200', '7700',
       '14600', '6300', '7100', '11800', '9400', '5500', '5800', '13200',
       '12500', '5600', '7000', '11900', '10400', '10700', '12700',
       '6800', '6500', '13600', '10200', '9000', '14900', '8200', '15200',
       '5000', '16300', '12400', '\t8400', '10500', '4200', '4700',
       '10900', '8100', '9500', '2200', '12800', '11200', '19100', '\t?',
       '12300', '16700', '2600', '26400', '8800', '7400', '4900', '8000',
       '12000', '15700', '4100', '5700', '11500', '5400', '10800', '9900',
       '5200', '5900', '9300', '9700', '5100', '6600'], dtype=object)

In [24]:
p=dataset['White Blood Cell Count'].mode()[0]
p

'9800'

In [25]:
dataset['White Blood Cell Count'].replace(['\t?','\t8400'],[9800,9800],inplace=True)

In [26]:
dataset['White Blood Cell Count'].fillna(dataset['White Blood Cell Count'].mode()[0],inplace=True)

In [27]:
dataset['Red Blood Cell Count'].unique()

array(['5.2', nan, '3.9', '4.6', '4.4', '5', '4', '3.7', '3.8', '3.4',
       '2.6', '2.8', '4.3', '3.2', '3.6', '4.1', '4.9', '2.5', '4.2',
       '4.5', '3.1', '4.7', '3.5', '6', '2.1', '5.6', '2.3', '2.9', '2.7',
       '8', '3.3', '3', '2.4', '4.8', '\t?', '5.4', '6.1', '6.2', '6.3',
       '5.1', '5.8', '5.5', '5.3', '6.4', '5.7', '5.9', '6.5'],
      dtype=object)

In [28]:
q=dataset['Red Blood Cell Count'].mode()[0]
q

'5.2'

In [29]:
dataset['Red Blood Cell Count'].replace(['\t?'],[5.2],inplace=True)

In [30]:
dataset['Red Blood Cell Count'].fillna(dataset['Red Blood Cell Count'].mode()[0],inplace=True)

In [31]:
dataset['Hypertension'].fillna(dataset['Hypertension'].mode()[0],inplace=True)

In [32]:
dataset['Appetite'].fillna(dataset['Appetite'].mode()[0],inplace=True)

In [33]:
dataset['Pedal Edema'].fillna(dataset['Pedal Edema'].mode()[0],inplace=True)

In [34]:
dataset['Anemia'].fillna(dataset['Anemia'].mode()[0],inplace=True)

In [35]:
dataset.isnull().any()

age                       False
Blood Pressure            False
Specific Gravity           True
Albumin                   False
Sugar                     False
Red Blood Cells           False
Pus Cell                  False
Pus Cell clumps           False
Bacteria                  False
Blood Glucose Random      False
Blood Urea                False
Serum Creatinine          False
Sodium                    False
Potassium                 False
Hemoglobin                False
Packed Cell Volume        False
White Blood Cell Count    False
Red Blood Cell Count      False
Hypertension              False
Appetite                  False
Pedal Edema               False
Anemia                    False
Class                     False
dtype: bool

In [36]:
dataset.head(5)

age  Blood Pressure  Specific Gravity  Albumin  Sugar Red Blood Cells  \
0  48.0            80.0             1.020      1.0    0.0          normal   
1   7.0            50.0             1.020      4.0    0.0          normal   
2  62.0            80.0             1.010      2.0    3.0          normal   
3  48.0            70.0             1.005      4.0    0.0          normal   
4  51.0            80.0             1.010      2.0    0.0          normal   

   Pus Cell Pus Cell clumps     Bacteria  Blood Glucose Random  ...  \
0    normal     not present  not present                 121.0  ...   
1    normal     not present  not present                 121.0  ...   
2    normal     not present  not present                 423.0  ...   
3  abnormal         present  not present                 117.0  ...   
4    normal     not present  not present                 106.0  ...   

   Potassium  Hemoglobin  Packed Cell Volume  White Blood Cell Count  \
0        4.4        15.4                  44                    7800   
1        4.4        11.3                  38                    6000   
2        4.4         9.6                  31                    7500   
3        2.5        11.2                  32                    6700   
4        4.4        11.6                  35                    7300   

   Red Blood Cell Count Hypertension Appetite Pedal Edema Anemia Class  
0                   5.2          yes     good          no     no     1  
1                   5.2           no     good          no     no     1  
2                   5.2           no     poor          no    yes     1  
3                   3.9          yes     poor         yes    yes     1  
4                   4.6           no     good          no     no     1  

[5 rows x 23 columns]

In [37]:
dataset['Red Blood Cells'].unique()

array(['normal', 'abnormal'], dtype=object)

In [38]:
dataset['Pus Cell'].unique()

array(['normal', 'abnormal'], dtype=object)

In [39]:
dataset['Pus Cell clumps'].unique()

array(['not present', 'present'], dtype=object)

In [40]:
dataset['Bacteria'].unique()

array(['not present', 'present'], dtype=object)

In [41]:
dataset['Hypertension'].unique()

array(['yes', 'no'], dtype=object)

In [42]:
dataset['Appetite'].unique()

array(['good', 'poor', 'moderate'], dtype=object)

In [43]:
dataset['Pedal Edema'].unique()

array(['no', 'yes'], dtype=object)

In [44]:
dataset['Anemia'].unique()

array(['no', 'yes'], dtype=object)

In [45]:
#Label Encoder

In [46]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset['Red Blood Cells'] = le.fit_transform(dataset['Red Blood Cells'])

In [47]:
dataset['Pus Cell'] = le.fit_transform(dataset['Pus Cell'])

In [48]:
dataset['Pus Cell clumps'] = le.fit_transform(dataset['Pus Cell clumps'])

In [49]:
dataset['Bacteria'] = le.fit_transform(dataset['Bacteria'])

In [50]:
dataset['Hypertension'] = le.fit_transform(dataset['Hypertension'])

In [51]:
dataset['Appetite'] = le.fit_transform(dataset['Appetite'])

In [52]:
dataset['Pedal Edema'] = le.fit_transform(dataset['Pedal Edema'])

In [53]:
dataset['Anemia'] = le.fit_transform(dataset['Anemia'])

In [54]:
dataset.head(10)

age  Blood Pressure  Specific Gravity  Albumin  Sugar  Red Blood Cells  \
0  48.0            80.0             1.020      1.0    0.0                1   
1   7.0            50.0             1.020      4.0    0.0                1   
2  62.0            80.0             1.010      2.0    3.0                1   
3  48.0            70.0             1.005      4.0    0.0                1   
4  51.0            80.0             1.010      2.0    0.0                1   
5  60.0            90.0             1.015      3.0    0.0                1   
6  68.0            70.0             1.010      0.0    0.0                1   
7  24.0            80.0             1.015      2.0    4.0                1   
8  52.0           100.0             1.015      3.0    0.0                1   
9  53.0            90.0             1.020      2.0    0.0                0   

   Pus Cell  Pus Cell clumps  Bacteria  Blood Glucose Random  ...  Potassium  \
0         1                0         0                 121.0  ...        4.4   
1         1                0         0                 121.0  ...        4.4   
2         1                0         0                 423.0  ...        4.4   
3         0                1         0                 117.0  ...        2.5   
4         1                0         0                 106.0  ...        4.4   
5         1                0         0                  74.0  ...        3.2   
6         1                0         0                 100.0  ...        4.0   
7         0                0         0                 410.0  ...        4.4   
8         0                1         0                 138.0  ...        4.4   
9         0                1         0                  70.0  ...        3.7   

   Hemoglobin  Packed Cell Volume  White Blood Cell Count  \
0        15.4                  44                    7800   
1        11.3                  38                    6000   
2         9.6                  31                    7500   
3        11.2                  32                    6700   
4        11.6                  35                    7300   
5        12.2                  39                    7800   
6        12.4                  36                    9800   
7        12.4                  44                    6900   
8        10.8                  33                    9600   
9         9.5                  29                   12100   

   Red Blood Cell Count Hypertension Appetite Pedal Edema  Anemia  Class  
0                   5.2            1        0           0       0      1  
1                   5.2            0        0           0       0      1  
2                   5.2            0        2           0       1      1  
3                   3.9            1        2           1       1      1  
4                   4.6            0        0           0       0      1  
5                   4.4            1        0           1       0      1  
6                   5.2            0        0           0       0      1  
7                     5            0        0           1       0      1  
8                     4            1        0           0       1      1  
9                   3.7            1        2           0       1      1  

[10 rows x 23 columns]

In [55]:
x = dataset.iloc[:,0:22].values

In [56]:
y = dataset.iloc[:,22].values

In [57]:
x

array([[48.0, 80.0, 1.02, ..., 0, 0, 0],
       [7.0, 50.0, 1.02, ..., 0, 0, 0],
       [62.0, 80.0, 1.01, ..., 2, 0, 1],
       ...,
       [12.0, 80.0, 1.02, ..., 0, 0, 0],
       [17.0, 60.0, 1.025, ..., 0, 0, 0],
       [58.0, 80.0, 1.025, ..., 0, 0, 0]], dtype=object)

In [58]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [59]:
x.shape

(400, 22)

In [60]:
from sklearn.preprocessing import OneHotEncoder
one = OneHotEncoder()
a = one.fit_transform(x[:,19:20]).toarray()


In [61]:
x = np.delete(x,19,axis = 1)
x

array([[48.0, 80.0, 1.02, ..., 1, 0, 0],
       [7.0, 50.0, 1.02, ..., 0, 0, 0],
       [62.0, 80.0, 1.01, ..., 0, 0, 1],
       ...,
       [12.0, 80.0, 1.02, ..., 0, 0, 0],
       [17.0, 60.0, 1.025, ..., 0, 0, 0],
       [58.0, 80.0, 1.025, ..., 0, 0, 0]], dtype=object)

In [62]:
x = np.concatenate((a,x),axis = 1)

In [63]:
a

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [64]:
x

array([[1.0, 0.0, 0.0, ..., 1, 0, 0],
       [1.0, 0.0, 0.0, ..., 0, 0, 0],
       [0.0, 0.0, 1.0, ..., 0, 0, 1],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 0, 0],
       [1.0, 0.0, 0.0, ..., 0, 0, 0],
       [1.0, 0.0, 0.0, ..., 0, 0, 0]], dtype=object)

In [65]:
x.shape

(400, 24)

In [66]:
y.shape

(400,)

In [67]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size =0.2,random_state = 0)

In [68]:
x_test.shape

(80, 24)

In [69]:
y_test.shape

(80,)

In [70]:
x_train.shape

(320, 24)

In [71]:
y_train.shape

(320,)

In [72]:
x_train[:,20:24]

array([['5.2', 0, 0, 0],
       ['5.2', 0, 0, 0],
       ['5.2', 0, 1, 0],
       ...,
       ['4.4', 0, 0, 0],
       ['5.2', 0, 0, 0],
       ['4.9', 0, 0, 0]], dtype=object)

In [73]:
#Feature Scaling

In [74]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [75]:
x_train[:20:24]

array([[ 0.51460872, -0.09728167, -0.5       , -1.59195906, -1.18916962,
         0.41474178, -0.65727351, -0.3767911 ,  0.35043832,  0.48038446,
        -0.33333333, -0.21389632, -0.35689278, -0.60288143, -0.40626351,
        -0.40128499, -0.07159542,  0.81297265,  0.05699897,  0.1157256 ,
         0.33615568, -0.7540739 , -0.4853053 , -0.3992747 ]])